POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "testing the post modification",
    "authur": "Rihat Hurdson",
    "url": "https://nogarea.com",
    "likes": 6

}